//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGia
    {
        public int MaBangGia { get; set; }
        public Nullable<int> MaLoaiPhong { get; set; }
        public Nullable<System.TimeSpan> GioBatDau { get; set; }
        public Nullable<System.TimeSpan> GioKetThuc { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
