//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MaChiTiet { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public Nullable<int> MaDichVu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
