//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using QL_QuanKaraoke_BETA_1.ViewModel;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows.Media.Imaging;

    public partial class DichVu : BaseViewModel
    {
        public DichVu()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }

        public int MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> TonKho { get; set; }
        public Nullable<int> CanhBaoTonKho { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<bool> IsEnable { get; set; }

        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }

        public BitmapImage HinhAnhBitmap
        {
            get
            {
                try
                {
                    if (string.IsNullOrEmpty(HinhAnh))
                        return null;

                    string fullPath = Path.Combine(
                        AppDomain.CurrentDomain.BaseDirectory,
                        HinhAnh
                    );

                    return new BitmapImage(new Uri(fullPath, UriKind.Absolute));
                }
                catch
                {
                    return null;
                }
            }
        }
        // Các prop viết thêm 

        private int _soLuong;

        public int SoLuong
        {
            get { return _soLuong; }
            set { _soLuong = value; OnPropertyChanged(); }
        }
        public bool TonKhoThap
        {
            get
            {
                return (TonKho ?? 0) <= (CanhBaoTonKho ?? 0);
            }
        }
    }

}
