//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangThanhVien
    {
        public HangThanhVien()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int MaHang { get; set; }
        public string TenHang { get; set; }
        public Nullable<double> PhanTramGiamGia { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
