//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuChuyenPhong
    {
        public int MaLichSu { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public Nullable<int> MaPhongCu { get; set; }
        public Nullable<int> MaPhongMoi { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
