//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhong
    {
        public LoaiPhong()
        {
            this.BangGias = new HashSet<BangGia>();
            this.Phongs = new HashSet<Phong>();
        }
    
        public int MaLoaiPhong { get; set; }
        public string TenLoai { get; set; }
        public Nullable<decimal> GiaCoBan { get; set; }
    
        public virtual ICollection<BangGia> BangGias { get; set; }
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
