//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int MaLog { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<System.DateTime> ThoiGianDangNhap { get; set; }
        public Nullable<System.DateTime> ThoiGianDangXuat { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
