//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using QL_QuanKaraoke_BETA_1.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class NhanVien : BaseViewModel
    {
        public NhanVien()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.LoginLogs = new HashSet<LoginLog>();
            this.SystemLogs = new HashSet<SystemLog>();
        }

        public int MaNhanVien { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }

        private string _chucVu;

        public string ChucVu
        {
            get { return _chucVu; }
            set { _chucVu = value; OnPropertyChanged(); }
        }

        public Nullable<int> MaRole { get; set; }
        private int _trangThai { get; set; }
        public int TrangThai
        {
            get => _trangThai;
            set { _trangThai = value; OnPropertyChanged(); }
        }

        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<SystemLog> SystemLogs { get; set; }
    }
}
