//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public Phong()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> MaLoaiPhong { get; set; }
        public Nullable<int> SucChua { get; set; }
        public string TrangThai { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
