//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanKaraoke_BETA_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int MaRole { get; set; }
        public string TenRole { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
